### ISSUE TITLE
DoS, locked funds

### ISSUE THREAD

**Issue by brockelmore** [rbcp18/zero-collateral-v1#1]
It is trivial to lock the entire balance of the contract by creating enough borrow accounts that when looping over borrows, the contract always runs out of gas. 

Significant redesign is needed prior to mainnet deployment. I suggest turning borrows into a mapping and never force undefined length for loops.

Would necessitate a different liquidation model as well

**Comment by brockelmore** [comment]
See [here](https://github.com/rbcp18/zero-collateral-v1/blob/09e1f08c2d40c36202c8306439c22742cde68a1b/contracts/ZeroCollateral.sol#L311-L318)

[here](https://github.com/rbcp18/zero-collateral-v1/blob/09e1f08c2d40c36202c8306439c22742cde68a1b/contracts/ZeroCollateral.sol#L331-L336)

[here](https://github.com/rbcp18/zero-collateral-v1/blob/09e1f08c2d40c36202c8306439c22742cde68a1b/contracts/ZeroCollateral.sol#L245-L249)

[and here.](https://github.com/rbcp18/zero-collateral-v1/blob/09e1f08c2d40c36202c8306439c22742cde68a1b/contracts/ZeroCollateral.sol#L283-L287)

**Comment by rbcp18** [comment]
Thanks for addressing this issue. Our team is looking at turning borrows into a mapping of UUID per borrow, in addition to creating a second mapping of active borrow to account address.

**Comment by rbcp18** [comment]
@brockelmore looping over borrows is removed, and replaced with a mapping of the borrower struct

**Comment by brockelmore** [comment]
> @brockelmore looping over borrows is removed, and replaced with a mapping of the borrower struct

Awesome!
